### PR TITLE
computing covariance/errors with weighted events

### PR DESCRIPTION
**Pull request by marinang**
## Proposed Changes

Implements the correction to the covariance matrix described in this [paper](https://arxiv.org/pdf/1911.01303.pdf) in equation 18, for weighted events (without uncertainties). 

## Tests added

  - add test with weights in test_covariance
  
## Checklist

 - [x] change approved
 - [x] implementation finished
 - [x] correct namespace imported
 - [x] tests added
 - [x] CHANGELOG updated

### CODE REVIEW

**Comment by mayou36** [comment]
Looks good, I fixed the conflict. Let's merge and we can refactor things out later, let's put it into testing mode with the public ;)

**Comment by marinang** [comment]
@mayou36 yep agreed :)

**Comment by mayou36** [comment]
Okey, we don't have a test yet, right, or did you not push it? Otherwise I'll add something later

**Comment by marinang** [comment]
Right I didn't, I can also design a test later today.

**Review by mayou36 — APPROVED** [review]

**Comment by marinang** [comment]
Maybe we should add a warning message to say that this is experimental?

**Pull request merged**
