### PR TITLE
Doc redesign

### PR DESCRIPTION
**Pull request by SebastianJL**
## Proposed Changes

New docs are visible here: https://zfit.readthedocs.io/en/doc-redesign/index.html

 - Use the pydata sphinx theme.
 - Write the api by hand.
  
## Checklist

 - [ ] change approved
 - [ ] implementation finished
 - [ ] Finish api.
 - [ ] Fix issues with linking in the api.
 - [ ] CHANGELOG updated

### CODE REVIEW

**Comment by SebastianJL** [comment]
This is still WIP, but I thought I'd create a pull request so that @mayou36 (and others?) have somewhere where they review and request changes.

**Comment by marinang** [comment]
Hi @SebastianJL,  may I suggest you to add the following `sphinx_copybutton` extension in `conf.py` as it allows to copy the pieces of codes and removes the ">>>" :)?

**Comment by SebastianJL** [comment]
> sphinx_copybutton

Done. Very nice extension.

**Comment by apuignav** [comment]
This looks great! Is the left hand sidebar maybe a bit too big? I see a lot of empty space on my desktop.

**Comment by SebastianJL** [comment]
> This looks great! Is the left hand sidebar maybe a bit too big? I see a lot of empty space on my desktop.

I would have to agree with you. I am using the pydata_sphinx_theme, developed by Pandas. They are working on more personalization options, but last time I checked this was not yet released. I'll write it down and come back to it as soon as they release extensive customisation of the theme.

**Pull request merged**
