### PR TITLE
Changes in doc for the new constraint classes

### PR DESCRIPTION
**Pull request by marinang**
I fixed typos and I changed parts that didn't look nice in the doc for the constraints.

See https://zfit.github.io/zfit/model.html, and https://zfit.github.io/zfit/loss.html.

### CODE REVIEW

**Comment by apuignav** [comment]
Nice catch! I was wondering if you could include a small example on how to actually write a custom constraint. What do you think?

**Comment by marinang** [comment]
@apuignav like from function that returns a Tensor? Do you have a good constraint example?

**Comment by apuignav** [comment]
I was thinking even explaining a bit the `GaussianConstraint`, but it's actually quite complex. What about a simple parameter inequality constraint? Something like: if the parameter value is above a certain value, make the logL explode. This would be extremely useful for setting limits on composed parameters, for example.

**Comment by marinang** [comment]
Good I was thinking about something similar. I'll write the example.

**Comment by mayou36** [comment]
Looks nice! As soon as you wanna merge, just request the review.

**Pull request merged**
